### ISSUE TITLE
CUDA 8 installation on ubuntu 18.04

### ISSUE THREAD

**Issue by ghost** [muhakbaryasin/compile-gcc-5.3.0-ubuntu-18.04#1]
Thanks for sharing that.
Since I have a NVIDIA fermi architecture which the default cuda 9.1 on ubuntu 18.04 doesn't support anymore, I am willing to downgrade to cuda 8 too !

Did you install it using the .run file from nvidia website ?

Thanks.

**Comment by muhakbaryasin** [comment]
Ur welcome. 

Yep, I use .run file.
